export const DEFAULT_QUESTIONS = {
  es: {
    funny: [
      "Nombra 3 cosas que harías si fueras invisible por un día",
      "Nombra 3 superhéroes con poderes ridículos",
      "Nombra 3 excusas creativas para llegar tarde",
      "Nombra 3 cosas que nunca dirías en una primera cita",
      "Nombra 3 emojis que describan tu personalidad",
      "Nombra 3 cosas raras que comes o combinas",
      "Nombra 3 sonidos graciosos de animales",
      "Nombra 3 momentos embarazosos en público",
      "Nombra 3 chistes malos que conozcas",
      "Nombra 3 cosas que harías si fueras presidente por un día",
      "Nombra 3 superpoderes inútiles pero divertidos",
      "Nombra 3 cosas que te hacen reír sin control",
      "Nombra 3 imitaciones que sabes hacer",
      "Nombra 3 situaciones absurdas de películas",
      "Nombra 3 cosas que harías con un millón de dólares"
    ],
    'pop-culture': [
      "Nombra 3 películas de Marvel o DC",
      "Nombra 3 cantantes de reggaetón actuales",
      "Nombra 3 series de Netflix populares",
      "Nombra 3 memes famosos de internet",
      "Nombra 3 youtubers o streamers famosos",
      "Nombra 3 bandas de rock clásico",
      "Nombra 3 actores de Hollywood",
      "Nombra 3 películas de los 80s o 90s",
      "Nombra 3 programas de TV de tu infancia",
      "Nombra 3 videojuegos clásicos",
      "Nombra 3 personajes de Disney",
      "Nombra 3 sagas de películas famosas",
      "Nombra 3 reality shows",
      "Nombra 3 cantantes latinos",
      "Nombra 3 películas de terror"
    ],
    personal: [
      "Nombra 3 de tus comidas favoritas",
      "Nombra 3 países que quieres visitar",
      "Nombra 3 cosas que te hagan feliz",
      "Nombra 3 habilidades o talentos que tienes",
      "Nombra 3 momentos memorables de tu vida",
      "Nombra 3 cosas que te dan miedo",
      "Nombra 3 hobbies o pasatiempos",
      "Nombra 3 lugares favoritos en tu ciudad",
      "Nombra 3 metas para este año",
      "Nombra 3 cosas que valoras en un amigo",
      "Nombra 3 canciones favoritas",
      "Nombra 3 libros o autores que te gusten",
      "Nombra 3 cualidades de tu personalidad",
      "Nombra 3 cosas que harías en un día libre",
      "Nombra 3 sueños o aspiraciones"
    ],
    challenge: [
      "Nombra 3 países de América del Sur",
      "Nombra 3 animales que empiecen con 'E'",
      "Nombra 3 capitales europeas",
      "Nombra 3 elementos de la tabla periódica",
      "Nombra 3 planetas del sistema solar",
      "Nombra 3 deportes olímpicos de invierno",
      "Nombra 3 instrumentos de cuerda",
      "Nombra 3 colores del arcoíris",
      "Nombra 3 marcas de coches alemanes",
      "Nombra 3 frutas cítricas",
      "Nombra 3 tipos de dinosaurios",
      "Nombra 3 inventos importantes",
      "Nombra 3 ríos famosos del mundo",
      "Nombra 3 montañas más altas",
      "Nombra 3 desiertos del mundo"
    ],
    food: [
      "Nombra 3 ingredientes de una pizza",
      "Nombra 3 frutas tropicales",
      "Nombra 3 postres tradicionales",
      "Nombra 3 cosas que pones en un hot dog",
      "Nombra 3 bebidas sin alcohol",
      "Nombra 3 tipos de pasta",
      "Nombra 3 verduras verdes",
      "Nombra 3 platos mexicanos",
      "Nombra 3 alimentos picantes",
      "Nombra 3 cosas dulces que te gusten",
      "Nombra 3 comidas rápidas",
      "Nombra 3 ingredientes para una ensalada",
      "Nombra 3 tipos de pan",
      "Nombra 3 marcas de refrescos",
      "Nombra 3 cosas que comes en el desayuno"
    ],
    travel: [
      "Nombra 3 playas famosas del mundo",
      "Nombra 3 monumentos históricos",
      "Nombra 3 ciudades de España",
      "Nombra 3 cosas imprescindibles en un viaje",
      "Nombra 3 aerolíneas internacionales",
      "Nombra 3 lugares turísticos de tu país",
      "Nombra 3 tipos de alojamiento vacacional",
      "Nombra 3 cosas que te gusta hacer en vacaciones",
      "Nombra 3 ciudades que nunca olvidarás",
      "Nombra 3 países que hablan español",
      "Nombra 3 islas paradisíacas",
      "Nombra 3 culturas que te interesen",
      "Nombra 3 actividades de aventura",
      "Nombra 3 cosas que odias de viajar",
      "Nombra 3 recuerdos de viaje"
    ],
    random: [
      "Nombra 3 cosas que encuentras en una oficina",
      "Nombra 3 instrumentos musicales",
      "Nombra 3 deportes de equipo",
      "Nombra 3 aplicaciones de tu teléfono",
      "Nombra 3 cosas que compras en un supermercado",
      "Nombra 3 medios de transporte",
      "Nombra 3 profesiones o trabajos",
      "Nombra 3 cosas redondas",
      "Nombra 3 objetos que flotan",
      "Nombra 3 cosas que usas todos los días",
      "Nombra 3 herramientas del hogar",
      "Nombra 3 materiales de construcción",
      "Nombra 3 cosas que brillan en la oscuridad",
      "Nombra 3 objetos cuadrados",
      "Nombra 3 cosas que huelen bien"
    ]
  },
  en: {
    funny: [
      "Name 3 things you would do if you were invisible for a day",
      "Name 3 superheroes with ridiculous powers",
      "Name 3 creative excuses for being late",
      "Name 3 things you'd never say on a first date",
      "Name 3 emojis that describe your personality",
      "Name 3 weird food combinations you eat",
      "Name 3 funny animal sounds",
      "Name 3 embarrassing moments in public",
      "Name 3 bad jokes you know",
      "Name 3 things you'd do if president for a day",
      "Name 3 useless but fun superpowers",
      "Name 3 things that make you laugh uncontrollably",
      "Name 3 impressions you can do",
      "Name 3 absurd situations from movies",
      "Name 3 things you'd do with a million dollars"
    ],
    'pop-culture': [
      "Name 3 Marvel or DC movies",
      "Name 3 current reggaeton singers",
      "Name 3 popular Netflix series",
      "Name 3 famous internet memes",
      "Name 3 famous youtubers or streamers",
      "Name 3 classic rock bands",
      "Name 3 Hollywood actors",
      "Name 3 movies from the 80s or 90s",
      "Name 3 TV shows from your childhood",
      "Name 3 classic video games",
      "Name 3 Disney characters",
      "Name 3 famous movie franchises",
      "Name 3 reality shows",
      "Name 3 Latin singers",
      "Name 3 horror movies"
    ],
    personal: [
      "Name 3 of your favorite foods",
      "Name 3 countries you want to visit",
      "Name 3 things that make you happy",
      "Name 3 skills or talents you have",
      "Name 3 memorable moments in your life",
      "Name 3 things you're afraid of",
      "Name 3 hobbies or pastimes",
      "Name 3 favorite places in your city",
      "Name 3 goals for this year",
      "Name 3 qualities you value in a friend",
      "Name 3 favorite songs",
      "Name 3 books or authors you like",
      "Name 3 qualities of your personality",
      "Name 3 things you'd do on a free day",
      "Name 3 dreams or aspirations"
    ],
    challenge: [
      "Name 3 South American countries",
      "Name 3 animals starting with 'E'",
      "Name 3 European capitals",
      "Name 3 elements from the periodic table",
      "Name 3 planets in the solar system",
      "Name 3 winter Olympic sports",
      "Name 3 string instruments",
      "Name 3 colors of the rainbow",
      "Name 3 German car brands",
      "Name 3 citrus fruits",
      "Name 3 types of dinosaurs",
      "Name 3 important inventions",
      "Name 3 famous rivers of the world",
      "Name 3 highest mountains",
      "Name 3 deserts of the world"
    ],
    food: [
      "Name 3 pizza toppings",
      "Name 3 tropical fruits",
      "Name 3 traditional desserts",
      "Name 3 things you put on a hot dog",
      "Name 3 non-alcoholic drinks",
      "Name 3 types of pasta",
      "Name 3 green vegetables",
      "Name 3 Mexican dishes",
      "Name 3 spicy foods",
      "Name 3 sweet things you like",
      "Name 3 fast foods",
      "Name 3 ingredients for a salad",
      "Name 3 types of bread",
      "Name 3 soda brands",
      "Name 3 things you eat for breakfast"
    ],
    travel: [
      "Name 3 famous beaches in the world",
      "Name 3 historical monuments",
      "Name 3 cities in Spain",
      "Name 3 essential things for a trip",
      "Name 3 international airlines",
      "Name 3 tourist places in your country",
      "Name 3 types of vacation accommodation",
      "Name 3 things you like to do on vacation",
      "Name 3 cities you'll never forget",
      "Name 3 Spanish-speaking countries",
      "Name 3 paradise islands",
      "Name 3 cultures that interest you",
      "Name 3 adventure activities",
      "Name 3 things you hate about traveling",
      "Name 3 travel souvenirs"
    ],
    random: [
      "Name 3 things you find in an office",
      "Name 3 musical instruments",
      "Name 3 team sports",
      "Name 3 apps on your phone",
      "Name 3 things you buy at a supermarket",
      "Name 3 means of transportation",
      "Name 3 professions or jobs",
      "Name 3 round things",
      "Name 3 objects that float",
      "Name 3 things you use every day",
      "Name 3 household tools",
      "Name 3 building materials",
      "Name 3 things that glow in the dark",
      "Name 3 square objects",
      "Name 3 things that smell good"
    ]
  }
};
